name: 🚀 Release

on:
  push:
    branches: [master, alpha]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: 💾 Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: ⎔ Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: 📥 Download deps
      uses: bahmutov/npm-install@v1
      with:
        useLockFile: false

    - name: 🚀 Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 18
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
